title:            Agim Emruli's Blog
locale:           en_US
url:

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap


# Site owner
owner:
  name:           Agim Emruli
  avatar:         http://www.gravatar.com/avatar/7e983ca06b3bb09286ea83fbedb3c798.png
  bio:            Entrepreneur, Open-Source Developer, Software Craftsmann
  email:          agimemruli (at) gmail.com
  disqus_shortname: aemruli
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        aemruli
  facebook:       agim.emruli
  bing_verify:
  github:         aemruli
  stackoverflow:  
  linkedin:       agimemruli
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google:
    plus:    AgimEmruli
    analytics:
    verify:
# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: true
#highlighter: pygments

# https://github.com/mojombo/jekyll/wiki/Permalinks



include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
